### ISSUE TITLE
Getting "The server encountered an error. You may have inputted an invalid query." error when I try out the url in the initial api response

### ISSUE THREAD

**Issue by abhishekmg** [RemiixInc/screenshot#1]
Trying out the url provided in the usage response (https://s.vercel.app/api?url=https://google.com&width=1280&height=720) is still giving me `"The server encountered an error. You may have inputted an invalid query."` error . 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/34393560/182091898-f378fdb4-43ae-4d46-b07a-d5c30b52d5b8.png">

**Comment by RemiixInc** [comment]
Can you try again? It is working for me now. Thanks!

**Comment by abhishekmg** [comment]
Yep its working now , thanks ! @RemiixInc
